"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-09 16:15:21.113459+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("province", sa.String(length=80), nullable=False),
        sa.Column("zone_code", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cities")),
        sa.UniqueConstraint("name", name=op.f("uq_cities_name")),
    )
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("event_key", sa.String(length=200), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
        sa.UniqueConstraint("provider", "event_key", name=op.f("uq_webhook_events_provider")),
    )
    op.create_table(
        "vendors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("contact_name", sa.String(length=120), nullable=False),
        sa.Column("contact_phone_e164", sa.String(length=16), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("city_id", sa.Uuid(), nullable=True),
        sa.Column("address", sa.String(length=1000), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], name=op.f("fk_vendors_city_id_cities")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("CUSTOMER", "ADMIN", "VENDOR", name="role", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("full_name", sa.String(length=120), nullable=True),
        sa.Column("phone_e164", sa.String(length=16), nullable=True),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("password_hash", sa.String(length=200), nullable=True),
        sa.Column("totp_secret_enc", sa.String(length=300), nullable=True),
        sa.Column("google_sub", sa.String(length=64), nullable=True),
        sa.Column("vendor_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_review_account", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terms_version", sa.String(length=50), nullable=True),
        sa.Column("terms_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendors.id"], name=op.f("fk_users_vendor_id_vendors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("google_sub", name=op.f("uq_users_google_sub")),
        sa.UniqueConstraint("phone_e164", name=op.f("uq_users_phone_e164")),
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_vendor_id"), "users", ["vendor_id"], unique=False)
    op.create_table(
        "addresses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("recipient_name", sa.String(length=120), nullable=False),
        sa.Column("recipient_phone_e164", sa.String(length=16), nullable=False),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("area", sa.String(length=120), nullable=False),
        sa.Column("street_address", sa.String(length=1000), nullable=False),
        sa.Column("landmark", sa.String(length=120), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"], ["cities.id"], name=op.f("fk_addresses_city_id_cities")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_addresses_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_addresses")),
    )
    op.create_index(op.f("ix_addresses_user_id"), "addresses", ["user_id"], unique=False)
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["users.id"], name=op.f("fk_app_settings_updated_by_id_users")
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_settings")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "actor_role",
            sa.Enum("CUSTOMER", "ADMIN", "VENDOR", name="role", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=60), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_logs_actor_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"), "audit_logs", ["actor_user_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=10), nullable=False),
        sa.Column("push_token", sa.String(length=4096), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_devices_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("push_token", name=op.f("uq_devices_push_token")),
    )
    op.create_index(op.f("ix_devices_user_id"), "devices", ["user_id"], unique=False)
    op.create_table(
        "otp_challenges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("phone_e164", sa.String(length=16), nullable=False),
        sa.Column("purpose", sa.String(length=10), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_otp_challenges_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_otp_challenges")),
    )
    op.create_index(
        op.f("ix_otp_challenges_phone_e164"), "otp_challenges", ["phone_e164"], unique=False
    )
    op.create_table(
        "payout_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "PAID", name="payoutbatchstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("total_paisa", sa.BigInteger(), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_payout_batches_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendors.id"], name=op.f("fk_payout_batches_vendor_id_vendors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payout_batches")),
    )
    op.create_index(
        op.f("ix_payout_batches_vendor_id"), "payout_batches", ["vendor_id"], unique=False
    )
    op.create_table(
        "pricing_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_pricing_configs_created_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_configs")),
        sa.UniqueConstraint("version", name=op.f("uq_pricing_configs_version")),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "uploads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "AWAITING_PARTS",
                "VALIDATING",
                "VALID",
                "REJECTED",
                "ABORTED",
                "PURGED",
                name="uploadstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("object_key", sa.String(length=200), nullable=True),
        sa.Column("s3_upload_id", sa.String(length=1024), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("declared_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("part_count", sa.Integer(), nullable=False),
        sa.Column("client_page_count", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "rejection_code",
            sa.Enum(
                "TOO_LARGE",
                "SIZE_MISMATCH",
                "NOT_PDF",
                "CORRUPT",
                "ENCRYPTED",
                "NO_PAGES",
                "ACTIVE_CONTENT",
                "MALWARE",
                "SCAN_FAILED",
                name="uploadrejection",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("copyright_declared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_uploads_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploads")),
    )
    op.create_index(op.f("ix_uploads_status"), "uploads", ["status"], unique=False)
    op.create_index(op.f("ix_uploads_user_id"), "uploads", ["user_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("PRINT", "SOURCE", name="ordertype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_PAYMENT",
                "PLACED",
                "VERIFYING",
                "ASSIGNED",
                "IN_PRINT",
                "REJECTED",
                "REQUESTED",
                "QUOTED",
                "ACCEPTED",
                "SOURCING",
                "QUOTE_EXPIRED",
                "DECLINED",
                "UNAVAILABLE",
                "READY_FOR_DISPATCH",
                "DISPATCHED",
                "DELIVERED",
                "COMPLETED",
                "CANCELLED",
                "DELIVERY_FAILED",
                name="orderstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("upload_id", sa.Uuid(), nullable=True),
        sa.Column("book_title", sa.String(length=200), nullable=True),
        sa.Column("book_author", sa.String(length=120), nullable=True),
        sa.Column("book_isbn", sa.String(length=20), nullable=True),
        sa.Column("book_edition", sa.String(length=120), nullable=True),
        sa.Column("book_notes", sa.Text(), nullable=True),
        sa.Column(
            "preferred_paper",
            sa.Enum("LOCAL_WHITE", "IMPORTED_YELLOW", name="paper", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column(
            "preferred_binding",
            sa.Enum(
                "SOFTCOVER_PAPERBACK",
                "PREMIUM_HARDCOVER",
                name="binding",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("pages", sa.Integer(), nullable=True),
        sa.Column(
            "paper",
            sa.Enum("LOCAL_WHITE", "IMPORTED_YELLOW", name="paper", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column(
            "binding",
            sa.Enum(
                "SOFTCOVER_PAPERBACK",
                "PREMIUM_HARDCOVER",
                name="binding",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("copies", sa.Integer(), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum(
                "COD",
                "EASYPAISA",
                "JAZZCASH",
                "CARD",
                name="paymentmethod",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "payment_status",
            sa.Enum(
                "PENDING",
                "PAID",
                "FAILED",
                "REFUNDED",
                name="paymentstatus",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("pricing_config_version", sa.Integer(), nullable=True),
        sa.Column("price_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("total_paisa", sa.BigInteger(), nullable=True),
        sa.Column("ship_recipient_name", sa.String(length=120), nullable=True),
        sa.Column("ship_recipient_phone_e164", sa.String(length=16), nullable=True),
        sa.Column("ship_city_id", sa.Uuid(), nullable=True),
        sa.Column("ship_city_name", sa.String(length=80), nullable=False),
        sa.Column("ship_zone_code", sa.String(length=20), nullable=False),
        sa.Column("ship_area", sa.String(length=120), nullable=True),
        sa.Column("ship_street_address", sa.String(length=1000), nullable=True),
        sa.Column("ship_landmark", sa.String(length=120), nullable=True),
        sa.Column("vendor_id", sa.Uuid(), nullable=True),
        sa.Column("vendor_cost_paisa", sa.BigInteger(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("courier_code", sa.String(length=30), nullable=True),
        sa.Column("cn_number", sa.String(length=60), nullable=True),
        sa.Column("tracking_url", sa.String(length=500), nullable=True),
        sa.Column("courier_status", sa.String(length=120), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exit_reason", sa.String(length=500), nullable=True),
        sa.Column("pii_scrubbed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ship_city_id"], ["cities.id"], name=op.f("fk_orders_ship_city_id_cities")
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"], ["uploads.id"], name=op.f("fk_orders_upload_id_uploads")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users")),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendors.id"], name=op.f("fk_orders_vendor_id_vendors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("code", name=op.f("uq_orders_code")),
        sa.UniqueConstraint("upload_id", name=op.f("uq_orders_upload_id")),
    )
    op.create_index(op.f("ix_orders_cn_number"), "orders", ["cn_number"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_type"), "orders", ["type"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_index(op.f("ix_orders_vendor_id"), "orders", ["vendor_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "ORDER_STATUS",
                "QUOTE_READY",
                "UPLOAD_RESULT",
                "PAYMENT",
                name="notificationkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.String(length=500), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_notifications_order_id_orders"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "order_status_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "PENDING_PAYMENT",
                "PLACED",
                "VERIFYING",
                "ASSIGNED",
                "IN_PRINT",
                "REJECTED",
                "REQUESTED",
                "QUOTED",
                "ACCEPTED",
                "SOURCING",
                "QUOTE_EXPIRED",
                "DECLINED",
                "UNAVAILABLE",
                "READY_FOR_DISPATCH",
                "DISPATCHED",
                "DELIVERED",
                "COMPLETED",
                "CANCELLED",
                "DELIVERY_FAILED",
                name="orderstatus",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "PENDING_PAYMENT",
                "PLACED",
                "VERIFYING",
                "ASSIGNED",
                "IN_PRINT",
                "REJECTED",
                "REQUESTED",
                "QUOTED",
                "ACCEPTED",
                "SOURCING",
                "QUOTE_EXPIRED",
                "DECLINED",
                "UNAVAILABLE",
                "READY_FOR_DISPATCH",
                "DISPATCHED",
                "DELIVERED",
                "COMPLETED",
                "CANCELLED",
                "DELIVERY_FAILED",
                name="orderstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "actor",
            sa.Enum(
                "USER", "ADMIN", "VENDOR", "SYSTEM", name="actor", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_order_status_history_actor_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_status_history_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_history")),
    )
    op.create_index(
        op.f("ix_order_status_history_order_id"), "order_status_history", ["order_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "COD",
                "EASYPAISA",
                "JAZZCASH",
                "CARD",
                name="paymentmethod",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("amount_paisa", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PAID",
                "FAILED",
                "REFUNDED",
                name="paymentstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider_ref", sa.String(length=120), nullable=True),
        sa.Column("checkout_url", sa.String(length=1000), nullable=True),
        sa.Column("failure_reason", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_payments_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("provider_ref", name=op.f("uq_payments_provider_ref")),
    )
    op.create_index(op.f("ix_payments_order_id"), "payments", ["order_id"], unique=False)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_table(
        "payout_batch_items",
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("amount_paisa", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["payout_batches.id"],
            name=op.f("fk_payout_batch_items_batch_id_payout_batches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_payout_batch_items_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("batch_id", "order_id", name=op.f("pk_payout_batch_items")),
        sa.UniqueConstraint("order_id", name=op.f("uq_payout_batch_items_order_id")),
    )
    op.create_table(
        "quotes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "ACCEPTED",
                "DECLINED",
                "EXPIRED",
                "CANCELLED",
                name="quotestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("pages", sa.Integer(), nullable=False),
        sa.Column(
            "paper",
            sa.Enum("LOCAL_WHITE", "IMPORTED_YELLOW", name="paper", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "binding",
            sa.Enum(
                "SOFTCOVER_PAPERBACK",
                "PREMIUM_HARDCOVER",
                name="binding",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("copies", sa.Integer(), nullable=False),
        sa.Column("sourcing_cost_paisa", sa.BigInteger(), nullable=False),
        sa.Column("calculated_goods_paisa", sa.BigInteger(), nullable=False),
        sa.Column("goods_paisa", sa.BigInteger(), nullable=False),
        sa.Column("override_reason", sa.String(length=500), nullable=True),
        sa.Column("pricing_config_version", sa.Integer(), nullable=False),
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_quotes_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_quotes_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotes")),
    )
    op.create_index(op.f("ix_quotes_order_id"), "quotes", ["order_id"], unique=False)
    op.create_index(op.f("ix_quotes_status"), "quotes", ["status"], unique=False)
    op.create_table(
        "refunds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=True),
        sa.Column("amount_paisa", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSED", name="refundstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("processed_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_refunds_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_refunds_order_id_orders"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"], ["payments.id"], name=op.f("fk_refunds_payment_id_payments")
        ),
        sa.ForeignKeyConstraint(
            ["processed_by_id"], ["users.id"], name=op.f("fk_refunds_processed_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refunds")),
    )
    op.create_index(op.f("ix_refunds_order_id"), "refunds", ["order_id"], unique=False)
    op.create_index(op.f("ix_refunds_status"), "refunds", ["status"], unique=False)
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "entry_type",
            sa.Enum(
                "REVENUE",
                "COD_COLLECTED",
                "COD_REMITTED",
                "VENDOR_COST_ACCRUED",
                "VENDOR_PAYOUT",
                "REFUND",
                name="ledgerentrytype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("amount_paisa", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("payment_id", sa.Uuid(), nullable=True),
        sa.Column("refund_id", sa.Uuid(), nullable=True),
        sa.Column("payment_method", sa.String(length=20), nullable=True),
        sa.Column("courier_code", sa.String(length=30), nullable=True),
        sa.Column("vendor_id", sa.Uuid(), nullable=True),
        sa.Column("payout_batch_id", sa.Uuid(), nullable=True),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_ledger_entries_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_ledger_entries_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"], ["payments.id"], name=op.f("fk_ledger_entries_payment_id_payments")
        ),
        sa.ForeignKeyConstraint(
            ["payout_batch_id"],
            ["payout_batches.id"],
            name=op.f("fk_ledger_entries_payout_batch_id_payout_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["refund_id"], ["refunds.id"], name=op.f("fk_ledger_entries_refund_id_refunds")
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendors.id"], name=op.f("fk_ledger_entries_vendor_id_vendors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
    )
    op.create_index(
        op.f("ix_ledger_entries_entry_type"), "ledger_entries", ["entry_type"], unique=False
    )
    op.create_index(
        op.f("ix_ledger_entries_order_id"), "ledger_entries", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_ledger_entries_vendor_id"), "ledger_entries", ["vendor_id"], unique=False
    )
    op.create_index(
        "uq_ledger_once_per_order",
        "ledger_entries",
        ["order_id", "entry_type"],
        unique=True,
        postgresql_where=sa.text(
            "entry_type IN ('COD_COLLECTED', 'COD_REMITTED', 'VENDOR_COST_ACCRUED', 'VENDOR_PAYOUT')"
        ),
    )
    op.create_index(
        "uq_ledger_refund",
        "ledger_entries",
        ["refund_id"],
        unique=True,
        postgresql_where=sa.text("entry_type = 'REFUND'"),
    )
    op.create_index(
        "uq_ledger_revenue_payment",
        "ledger_entries",
        ["payment_id"],
        unique=True,
        postgresql_where=sa.text("entry_type = 'REVENUE'"),
    )
    # The ledger is append-only (docs/DECISIONS.md D-028): corrections are new entries.
    op.execute(
        """
        CREATE FUNCTION ledger_entries_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'ledger_entries is append-only';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER ledger_entries_append_only BEFORE UPDATE OR DELETE ON ledger_entries "
        "FOR EACH ROW EXECUTE FUNCTION ledger_entries_append_only()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS ledger_entries_append_only ON ledger_entries")
    op.execute("DROP FUNCTION IF EXISTS ledger_entries_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_ledger_revenue_payment",
        table_name="ledger_entries",
        postgresql_where=sa.text("entry_type = 'REVENUE'"),
    )
    op.drop_index(
        "uq_ledger_refund",
        table_name="ledger_entries",
        postgresql_where=sa.text("entry_type = 'REFUND'"),
    )
    op.drop_index(
        "uq_ledger_once_per_order",
        table_name="ledger_entries",
        postgresql_where=sa.text(
            "entry_type IN ('COD_COLLECTED', 'COD_REMITTED', 'VENDOR_COST_ACCRUED', 'VENDOR_PAYOUT')"
        ),
    )
    op.drop_index(op.f("ix_ledger_entries_vendor_id"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_order_id"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_entry_type"), table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index(op.f("ix_refunds_status"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_order_id"), table_name="refunds")
    op.drop_table("refunds")
    op.drop_index(op.f("ix_quotes_status"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_order_id"), table_name="quotes")
    op.drop_table("quotes")
    op.drop_table("payout_batch_items")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_order_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_order_status_history_order_id"), table_name="order_status_history")
    op.drop_table("order_status_history")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_orders_vendor_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_type"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_cn_number"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_uploads_user_id"), table_name="uploads")
    op.drop_index(op.f("ix_uploads_status"), table_name="uploads")
    op.drop_table("uploads")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("pricing_configs")
    op.drop_index(op.f("ix_payout_batches_vendor_id"), table_name="payout_batches")
    op.drop_table("payout_batches")
    op.drop_index(op.f("ix_otp_challenges_phone_e164"), table_name="otp_challenges")
    op.drop_table("otp_challenges")
    op.drop_index(op.f("ix_devices_user_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("app_settings")
    op.drop_index(op.f("ix_addresses_user_id"), table_name="addresses")
    op.drop_table("addresses")
    op.drop_index(op.f("ix_users_vendor_id"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_table("users")
    op.drop_table("vendors")
    op.drop_table("webhook_events")
    op.drop_table("cities")
    # ### end Alembic commands ###
